{"name": "CVE-2016-4445", "affected_release": [{"advisory": "RHSA-2016:1267", "release_date": "2016-06-21T00:00:00", "cpe": "cpe:/o:redhat:enterprise_linux:6", "product_name": "Red Hat Enterprise Linux 6", "package": "setroubleshoot-3.0.47-12.el6_8"}, {"advisory": "RHBA-2015:2287", "release_date": "2015-11-19T00:00:00", "cpe": "cpe:/o:redhat:enterprise_linux:7", "product_name": "Red Hat Enterprise Linux 7", "package": "setroubleshoot-3.2.24-1.1.el7"}], "public_date": "2016-06-21T00:00:00", "package_state": {"fix_state": "Not affected", "product_name": "Red Hat Enterprise Linux 5", "package_name": "setroubleshoot", "cpe": "cpe:/o:redhat:enterprise_linux:5"}, "acknowledgement": "\nThis issue was discovered by Red Hat Product Security.\n    ", "document_distribution": "Copyright \u00a9 2016 Red Hat, Inc. All rights reserved.", "upstream_fix": "setroubleshoot 3.2.23", "threat_severity": "Moderate", "bugzilla": {"url": "https://bugzilla.redhat.com/show_bug.cgi?id=1339183", "description": "\nCVE-2016-4445 setroubleshoot: insecure use of commands.getstatusoutput in sealert\n    ", "id": "1339183"}, "details": ["\nThe fix_lookup_id function in sealert in setroubleshoot before 3.2.23 allows local users to execute arbitrary commands as root by triggering an SELinux denial with a crafted file name, related to executing external commands with the commands.getstatusoutput function.\n    ", "\nA shell command injection flaw was found in the way the setroubleshoot executed external commands. A local attacker able to trigger certain SELinux denials could use this flaw to execute arbitrary code with root privileges.\n    "], "cwe": "CWE-77", "cvss": {"cvss_scoring_vector": "AV:L/AC:H/Au:N/C:C/I:C/A:C", "status": "verified", "cvss_base_score": "6.2"}}