{"name": "CVE-2013-4314", "public_date": "2013-09-04T00:00:00", "package_state": [{"fix_state": "Not affected", "product_name": "Red Hat Enterprise Linux OpenStack Platform 4.0", "package_name": "pyOpenSSL", "cpe": "cpe:/a:redhat:openstack:4"}, {"fix_state": "Not affected", "product_name": "Red Hat Gluster Storage 2.1", "package_name": "pyOpenSSL", "cpe": "cpe:/a:redhat:storage:2.1"}, {"fix_state": "Not affected", "product_name": "Red Hat Enterprise Linux 5", "package_name": "pyOpenSSL", "cpe": "cpe:/o:redhat:enterprise_linux:5"}, {"fix_state": "Not affected", "product_name": "Red Hat Enterprise Linux 6", "package_name": "pyOpenSSL", "cpe": "cpe:/o:redhat:enterprise_linux:6"}, {"fix_state": "Not affected", "product_name": "Red Hat Enterprise Linux 7", "package_name": "pyOpenSSL", "cpe": "cpe:/o:redhat:enterprise_linux:7"}], "document_distribution": "Copyright \u00a9 2016 Red Hat, Inc. All rights reserved.", "upstream_fix": "pyOpenSSL 0.13.1", "threat_severity": "Moderate", "bugzilla": {"url": "https://bugzilla.redhat.com/show_bug.cgi?id=1005325", "description": "\nCVE-2013-4314 pyOpenSSL: hostname check bypassing vulnerability\n    ", "id": "1005325"}, "details": ["\nThe X509Extension in pyOpenSSL before 0.13.1 does not properly handle a '\\0' character in a domain name in the Subject Alternative Name field of an X.509 certificate, which allows man-in-the-middle attackers to spoof arbitrary SSL servers via a crafted certificate issued by a legitimate Certification Authority.\n    "], "statement": "\nNot vulnerable. This issue did not affect the versions of pyOpenSSL as shipped with Red Hat Enterprise Linux 5 and 6.\n    ", "cvss": {"cvss_scoring_vector": "AV:N/AC:M/Au:N/C:N/I:P/A:N", "status": "draft", "cvss_base_score": "4.3"}}