{"public_date": "2014-03-27T00:00:00", "name": "CVE-2014-0105", "affected_release": [{"advisory": "RHSA-2014:0442", "release_date": "2014-04-28T00:00:00", "cpe": "cpe:/a:redhat:openstack:3::el6", "product_name": "Red Hat Enterprise Linux OpenStack Platform 3.0", "package": "python-keystoneclient-1:0.2.3-8.el6ost"}, {"advisory": "RHSA-2014:0382", "release_date": "2014-04-09T00:00:00", "cpe": "cpe:/a:redhat:openstack:4::el6", "product_name": "Red Hat Enterprise Linux OpenStack Platform 4.0", "package": "python-keystoneclient-1:0.7.1-2.el6ost"}, {"advisory": "RHSA-2014:0409", "release_date": "2014-04-17T00:00:00", "cpe": "cpe:/a:redhat:storage:2.1:server:el6", "product_name": "Red Hat Storage Server 2.1", "package": "python-keystoneclient-1:0.7.1-2.el6ost"}], "acknowledgement": "\nRed Hat would like to thank the OpenStack project for reporting this issue. Upstream acknowledges Kieran Spear from the University of Melbourne as the original reporter.\n    ", "document_distribution": "Copyright \u00a9 2016 Red Hat, Inc. All rights reserved.", "upstream_fix": "python-keystone-client 0.7.0", "threat_severity": "Important", "bugzilla": {"url": "https://bugzilla.redhat.com/show_bug.cgi?id=1082165", "description": "\nCVE-2014-0105 python-keystoneclient: Potential context confusion in Keystone middleware\n    ", "id": "1082165"}, "details": ["\nThe auth_token middleware in the OpenStack Python client library for Keystone (aka python-keystoneclient) before 0.7.0 does not properly retrieve user tokens from memcache, which allows remote authenticated users to gain privileges in opportunistic circumstances via a large number of requests, related to an \"interaction between eventlet and python-memcached.\"\n    "], "cvss": {"cvss_scoring_vector": "AV:N/AC:M/Au:N/C:N/I:P/A:N", "status": "verified", "cvss_base_score": "4.3"}}