{"name": "CVE-2011-1521", "affected_release": [{"advisory": "RHSA-2011:0491", "release_date": "2011-05-05T00:00:00", "cpe": "cpe:/o:redhat:enterprise_linux:4", "product_name": "Red Hat Enterprise Linux 4", "package": "python-2.3.4-14.10.el4"}, {"advisory": "RHSA-2011:0492", "release_date": "2011-05-05T00:00:00", "cpe": "cpe:/o:redhat:enterprise_linux:5", "product_name": "Red Hat Enterprise Linux 5", "package": "python-2.4.3-44.el5"}, {"advisory": "RHSA-2011:0554", "release_date": "2011-05-19T00:00:00", "cpe": "cpe:/o:redhat:enterprise_linux:6", "product_name": "Red Hat Enterprise Linux 6", "package": "python-2.6.6-20.el6"}], "public_date": "2011-03-24T00:00:00", "iava": "2012-A-0020", "document_distribution": "Copyright \u00a9 2016 Red Hat, Inc. All rights reserved.", "threat_severity": "Moderate", "bugzilla": {"url": "https://bugzilla.redhat.com/show_bug.cgi?id=690560", "description": "\nCVE-2011-1521 python (urllib, urllib2): Improper management of ftp:// and file:// URL schemes (Issue #11662)\n    ", "id": "690560"}, "details": ["\nThe urllib and urllib2 modules in Python 2.x before 2.7.2 and 3.x before 3.2.1 process Location headers that specify redirection to file: URLs, which makes it easier for remote attackers to obtain sensitive information or cause a denial of service (resource consumption) via a crafted URL, as demonstrated by the file:///etc/passwd and file:///dev/zero URLs.\n    "], "cvss": {"cvss_scoring_vector": "AV:N/AC:L/Au:N/C:P/I:N/A:P", "status": "verified", "cvss_base_score": "6.4"}}