{"name": "CVE-2016-10127", "public_date": "2017-01-10T00:00:00", "package_state": [{"fix_state": "Not affected", "product_name": "OpenStack 10.0 Tools for RHEL 7", "package_name": "python-pysaml2", "cpe": "cpe:/a:redhat:openstack:10"}, {"fix_state": "Not affected", "product_name": "Red Hat OpenStack Platform 11", "package_name": "python-pysaml2", "cpe": "cpe:/a:redhat:openstack:11"}, {"fix_state": "Not affected", "product_name": "Red Hat Enterprise Linux OpenStack Platform 7.0 (Kilo) for RHEL 7", "package_name": "python-pysaml2", "cpe": "cpe:/a:redhat:openstack:7"}, {"fix_state": "Not affected", "product_name": "Red Hat OpenStack Platform 8.0 (Liberty)", "package_name": "python-pysaml2", "cpe": "cpe:/a:redhat:openstack:8"}, {"fix_state": "Not affected", "product_name": "Red Hat OpenStack Platform 9.0", "package_name": "python-pysaml2", "cpe": "cpe:/a:redhat:openstack:9"}], "document_distribution": "Copyright \u00a9 2016 Red Hat, Inc. All rights reserved.", "threat_severity": "Moderate", "bugzilla": {"url": "https://bugzilla.redhat.com/show_bug.cgi?id=1411794", "description": "\nCVE-2016-10127 python-pysaml2: Vulnerable to XML external entity attack\n    ", "id": "1411794"}, "details": ["\nPySAML2 allows remote attackers to conduct XML external entity (XXE) attacks via a crafted SAML XML request or response.\n    "], "statement": "\nThis flaw resides in the XML Security Library (xmlsec1) and will be updated there; Red Hat OpenStack Platform is not affected.\n    ", "cwe": "CWE-611", "cvss3": {"status": "draft", "cvss3_scoring_vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:L/A:L", "cvss3_base_score": "7.3"}}