{"public_date": "2014-11-12T00:00:00", "name": "CVE-2014-3606", "acknowledgement": "\nThis issue was discovered by Francisco Alonso of Red Hat Product Security.\n    ", "package_state": [{"fix_state": "New", "product_name": "Red Hat Enterprise Linux 5", "package_name": "python-imaging", "cpe": "cpe:/o:redhat:enterprise_linux:5"}, {"fix_state": "New", "product_name": "Red Hat Enterprise Linux 6", "package_name": "python-imaging", "cpe": "cpe:/o:redhat:enterprise_linux:6"}, {"fix_state": "New", "product_name": "Red Hat Enterprise Linux 7", "package_name": "python-pillow", "cpe": "cpe:/o:redhat:enterprise_linux:7"}], "document_distribution": "Copyright \u00a9 2016 Red Hat, Inc. All rights reserved.", "threat_severity": "None", "bugzilla": {"url": "https://bugzilla.redhat.com/show_bug.cgi?id=1133306", "description": "\nCVE-2014-3606 python-pillow: flaw in _unop()\n    ", "id": "1133306"}, "details": ["\n** RESERVED ** This candidate has been reserved by an organization or individual that will use it when announcing a new security problem.  When the candidate has been publicized, the details for this candidate will be provided.\n    "], "cvss": {"cvss_scoring_vector": "AV:L/AC:L/Au:N/C:P/I:P/A:P", "status": "draft", "cvss_base_score": "4.6"}}