{"name": "CVE-2013-7338", "public_date": "2013-12-27T00:00:00", "package_state": [{"fix_state": "Not affected", "product_name": "Red Hat Software Collections 1 for Red Hat Enterprise Linux", "package_name": "python27-python", "cpe": "cpe:/a:redhat:rhel_software_collections:1"}, {"fix_state": "Will not fix", "product_name": "Red Hat Software Collections for Red Hat Enterprise Linux", "package_name": "python33-python", "cpe": "cpe:/a:redhat:rhel_software_collections:2"}, {"fix_state": "Not affected", "product_name": "Red Hat Enterprise Linux 5", "package_name": "python", "cpe": "cpe:/o:redhat:enterprise_linux:5"}, {"fix_state": "Not affected", "product_name": "Red Hat Enterprise Linux 6", "package_name": "python", "cpe": "cpe:/o:redhat:enterprise_linux:6"}, {"fix_state": "Not affected", "product_name": "Red Hat Enterprise Linux 7", "package_name": "python", "cpe": "cpe:/o:redhat:enterprise_linux:7"}], "document_distribution": "Copyright \u00a9 2016 Red Hat, Inc. All rights reserved.", "threat_severity": "Moderate", "bugzilla": {"url": "https://bugzilla.redhat.com/show_bug.cgi?id=1078014", "description": "\nCVE-2013-7338 python: malformed ZIP files could cause 100% CPU usage\n    ", "id": "1078014"}, "details": ["\nPython before 3.3.4 RC1 allows remote attackers to cause a denial of service (infinite loop and CPU consumption) via a file size value larger than the size of the zip file to the (1) ZipExtFile.read, (2) ZipExtFile.read(n), (3) ZipExtFile.readlines, (4) ZipFile.extract, or (5) ZipFile.extractall function.\n    "], "statement": "\nThis issue did not affect the versions of python as shipped with Red Hat Enterprise Linux 5, 6 and 7.\n    ", "cvss": {"cvss_scoring_vector": "AV:N/AC:M/Au:N/C:N/I:N/A:P", "status": "draft", "cvss_base_score": "4.3"}}