{"name": "CVE-2017-9462", "affected_release": [{"advisory": "RHSA-2017:1576", "release_date": "2017-06-27T00:00:00", "cpe": "cpe:/o:redhat:enterprise_linux:6", "product_name": "Red Hat Enterprise Linux 6", "package": "mercurial-1.4-5.el6_9"}, {"advisory": "RHSA-2017:1576", "release_date": "2017-06-27T00:00:00", "cpe": "cpe:/o:redhat:enterprise_linux:7", "product_name": "Red Hat Enterprise Linux 7", "package": "mercurial-2.6.2-7.el7_3"}], "public_date": "2017-04-18T00:00:00", "document_distribution": "Copyright \u00a9 2016 Red Hat, Inc. All rights reserved.", "upstream_fix": "mercurial 4.1.3", "threat_severity": "Important", "bugzilla": {"url": "https://bugzilla.redhat.com/show_bug.cgi?id=1459482", "description": "\nCVE-2017-9462 mercurial: Python debugger accessible to authorized users\n    ", "id": "1459482"}, "details": ["\nIn Mercurial before 4.1.3, \"hg serve --stdio\" allows remote authenticated users to launch the Python debugger, and consequently execute arbitrary code, by using --debugger as a repository name.\n    ", "\nA flaw was found in the way \"hg serve --stdio\" command in Mercurial handled command-line options. A remote, authenticated attacker could use this flaw to execute arbitrary code on the Mercurial server by using specially crafted command-line options.\n    "], "cwe": "CWE-284", "cvss3": {"status": "verified", "cvss3_scoring_vector": "CVSS:3.0/AV:N/AC:L/PR:L/UI:N/S:U/C:L/I:L/A:L", "cvss3_base_score": "6.3"}}