{"name": "CVE-2016-9013", "public_date": "2016-11-01T00:00:00", "package_state": [{"fix_state": "Not affected", "product_name": "Red Hat Ceph Storage 1.3", "package_name": "Django", "cpe": "cpe:/a:redhat:ceph_storage:1.3"}, {"fix_state": "Not affected", "product_name": "Red Hat Ceph Storage 2", "package_name": "Django", "cpe": "cpe:/a:redhat:ceph_storage:2"}, {"fix_state": "Not affected", "product_name": "Red Hat OpenStack Platform Operational Tools 10", "package_name": "python-django", "cpe": "cpe:/a:redhat:openstack-optools:10"}, {"fix_state": "Not affected", "product_name": "Red Hat Enterprise Linux OpenStack Platform 7.0 Operational Tools for RHEL 7", "package_name": "python-django", "cpe": "cpe:/a:redhat:openstack-optools:7"}, {"fix_state": "Not affected", "product_name": "Red Hat Enterprise Linux OpenStack Platform 8.0 Operational Tools for RHEL 7", "package_name": "python-django", "cpe": "cpe:/a:redhat:openstack-optools:8"}, {"fix_state": "Not affected", "product_name": "Red Hat OpenStack Platform Operational Tools 9", "package_name": "python-django", "cpe": "cpe:/a:redhat:openstack-optools:9"}, {"fix_state": "Not affected", "product_name": "OpenStack 10.0 Tools for RHEL 7", "package_name": "python-django", "cpe": "cpe:/a:redhat:openstack:10"}, {"fix_state": "Not affected", "product_name": "Red Hat Enterprise Linux OpenStack Platform 5.0 (Icehouse) for RHEL 6", "package_name": "python-django", "cpe": "cpe:/a:redhat:openstack:5"}, {"fix_state": "Not affected", "product_name": "Red Hat Enterprise Linux OpenStack Platform 6.0 (Juno) for RHEL 7", "package_name": "python-django", "cpe": "cpe:/a:redhat:openstack:6"}, {"fix_state": "Not affected", "product_name": "Red Hat Enterprise Linux OpenStack Platform 7.0 (Kilo) for RHEL 7", "package_name": "python-django", "cpe": "cpe:/a:redhat:openstack:7"}, {"fix_state": "Not affected", "product_name": "Red Hat OpenStack Platform 8.0 (Liberty)", "package_name": "python-django", "cpe": "cpe:/a:redhat:openstack:8"}, {"fix_state": "Not affected", "product_name": "Red Hat OpenStack Platform 9.0", "package_name": "python-django", "cpe": "cpe:/a:redhat:openstack:9"}, {"fix_state": "Will not fix", "product_name": "Red Hat Subscription Asset Manager 1", "package_name": "Django", "cpe": "cpe:/a:redhat:rhel_sam:1"}, {"fix_state": "Not affected", "product_name": "Red Hat Storage Console 2", "package_name": "Django", "cpe": "cpe:/a:redhat:rhscon:2"}, {"fix_state": "Not affected", "product_name": "Red Hat Storage Console 2", "package_name": "python-django", "cpe": "cpe:/a:redhat:rhscon:2"}], "acknowledgement": "\nRed Hat would like to thank the Django project for reporting this issue.\n    ", "document_distribution": "Copyright \u00a9 2016 Red Hat, Inc. All rights reserved.", "cvss3": {"status": "draft", "cvss3_scoring_vector": "CVSS:3.0/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:H/A:N", "cvss3_base_score": "7.4"}, "threat_severity": "Moderate", "bugzilla": {"url": "https://bugzilla.redhat.com/show_bug.cgi?id=1389414", "description": "\nCVE-2016-9013 python-django: user with hardcoded password created when running tests on Oracle\n    ", "id": "1389414"}, "details": ["\nDjango 1.8.x before 1.8.16, 1.9.x before 1.9.11, and 1.10.x before 1.10.3 use a hardcoded password for a temporary database user created when running tests with an Oracle database, which makes it easier for remote attackers to obtain access to the database server by leveraging failure to manually specify a password in the database settings TEST dictionary.\n    "], "upstream_fix": "Django 1.10.3, Django 1.9.11, Django 1.8.16", "cwe": "CWE-798", "cvss": {"cvss_scoring_vector": "AV:N/AC:H/Au:N/C:P/I:P/A:N", "status": "draft", "cvss_base_score": "4.0"}}