{"public_date": "2012-12-18T00:00:00", "name": "CVE-2012-3428", "affected_release": [{"advisory": "RHSA-2012:1591", "release_date": "2012-12-18T00:00:00", "product_name": "Red Hat JBoss Enterprise Application Platform 6 for RHEL 5 Server", "cpe": "cpe:/a:redhat:jboss_enterprise_application_platform:6::el5"}, {"advisory": "RHSA-2012:1592", "release_date": "2012-12-18T00:00:00", "product_name": "Red Hat JBoss Enterprise Application Platform 6 for RHEL 6 Server", "cpe": "cpe:/a:redhat:jboss_enterprise_application_platform:6::el6"}, {"advisory": "RHSA-2012:1594", "release_date": "2012-12-18T00:00:00", "product_name": "Red Hat JBoss Enterprise Application Platform 6.0", "cpe": "cpe:/a:redhat:jboss_enterprise_application_platform:6.0"}], "acknowledgement": "\nThis issue was discovered by Arun Neelicattu of the Red Hat Security Response Team.\n    ", "document_distribution": "Copyright \u00a9 2016 Red Hat, Inc. All rights reserved.", "threat_severity": "Moderate", "bugzilla": {"url": "https://bugzilla.redhat.com/show_bug.cgi?id=843358", "description": "\nCVE-2012-3428 JBoss: Datasource connection manager returns valid connection for wrong credentials when using security-domains\n    ", "id": "843358"}, "details": ["\nThe IronJacamar container before 1.0.12.Final for JBoss Application Server, when allow-multiple-users is enabled in conjunction with a security domain, does not use the credentials supplied in a getConnection function call, which allows remote attackers to obtain access to an arbitrary datasource connection in opportunistic circumstances via an invalid connection attempt.\n    "], "cvss": {"cvss_scoring_vector": "AV:N/AC:M/Au:N/C:N/I:P/A:N", "status": "verified", "cvss_base_score": "4.3"}}